### ISSUE TITLE
Rare execution failures while setting Scheduling Policy

### ISSUE THREAD

**Issue by einansgar** [jak0bw/os_assignment_1_cpu_io_scheduling#1]
In task 2, change of the scheduling policy from 0 to 1 resulted in following output for `sudo ./task2 1 20 51200 1 0 > /output_data/task2/SMALL_CACHE_NOSYNC` at the first execution of `make`

```
========= Initializing Benchmark =========
========= Trying to set Scheduling Policy to: 1 =========
Error when setting scheduling policy: Operation not permitted

```

After calling ` ./task2 1 20 51200 1 0 > /output_data/task2/SMALL_CACHE_NOSYNC` manually, also `make` works fine again.

If this error is reproduceable: How to fix it? 

If this is not reproduceable, should we try to find the reason?

edit: the error is reproducable. Use some cache_nosync together with multithreading. If it does not happen for the first `make` just try another time.

**Comment by jak0bw** [comment]
Fixed with commit 4fe45979f3cffa7e35e18154cf32379c9eca47b0.
